# Generated by Django 3.2.12 on 2022-02-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220209_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='postupdateevent',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
